### ISSUE TITLE
backport angular 2 unit testing capabilities

### ISSUE THREAD

**Issue by Hotell** [ngParty/ng-metadata#93]
- app logic migration is number 1 priority, what about testing?

currently we provide `renderFactory` which leverages angular 1 testing patterns.

We need do better and support https://angular.io/docs/ts/latest/api/testing/

**Comment by aciccarello** [comment]
Do you have a list of the specific testing APIs you'd like to implement? The [inject](https://angular.io/docs/ts/latest/api/core/testing/inject-function.html) and [beforeEachProviders](https://angular.io/docs/ts/latest/api/core/testing/beforeEachProviders-function.html) functions looks like good ones to start with.

Also, your docs link is  broken :cry:. Here's all of the testing APIs: https://angular.io/docs/ts/latest/api/#!?apiFilter=testing

**Comment by Hotell** [comment]
yes, those two are the primary ones I guess. In the meantime you can do something similar with little utility method https://hotell.gitbooks.io/ng-metadata/content/docs/api/testing/function.html see that `queryByDirective` at the end.

What link is broken? Anyway if you found something broken, file an issue or even better submit a PR. It doesn't hurt ;)

**Comment by aciccarello** [comment]
Good to know :smiley: . And the docs link is the one in this issue to the Angular Docs.

**Comment by Hotell** [comment]
oh thanks for pointing that out, updated!

**Comment by Hotell** [comment]
So it looks like I've made a very good decision to move this to 2.1 because ng2 RC.4 was just released with another set of breaking changes https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc4-2016-06-30

**Comment by aciccarello** [comment]
Good call. Overall, I'm glad to see the API not being so tightly bound to jasmine.

> Additionally, beforeEachProviders is also deprecated, as it is specific to the testing framework. Instead, use the new addProviders method directly.
> 
> Before:
> 
> ```TypeScript
> import {beforeEachProviders, it, describe, inject} from '@angular/testing/core';
> 
> describe('my code', () => {
>   beforeEachProviders(() => [MyService]);
> 
>   it('does stuff', inject([MyService], (service) => {
>     // actual test
>   });
> });
> ```
> 
> After:
> 
> ```TypeScript
> import {addProviders, inject} from '@angular/testing/core';
> 
> describe('my code', () => {
>   beforeEach(() => {
>     addProviders([MyService]);
>   });
> 
>   it('does stuff', inject([MyService], (service) => {
>     // actual test
>   });
> });
> ```

**Comment by aciccarello** [comment]
Was thinking about this today. Since [RC5](https://github.com/angular/angular/compare/2.0.0-rc.4...2.0.0-rc.5) brought more breaking changes to testing, here's what I see as the top testing features to implement.

## @angular/core/testing
- [inject](https://angular.io/docs/ts/latest/api/core/testing/inject-function.html)
- [TestBed](https://angular.io/docs/ts/latest/api/core/testing/TestBed-class.html) (experimental)
- [ComponentFixture](https://angular.io/docs/ts/latest/api/core/testing/ComponentFixture-class.html)

Some of the methods of `TestBed` refer to the RC5 modules but the implementation could be routed to `angular.mock.module` and be updated when #126 is implemented. There are a lot of methods/properties but we'd only need the main ones.

```TypeScript
interface TestBed {
  configureTestingModule: (moduleDef: { providers?: any[]; declarations?: any[]; imports?: any[]; }) => void;
  createComponent: (component: T) => ComponentFixture;
}
```

Here's the ng-metadata interface I imagine for `ComponentFixture`. I may be missing some ways that the [`ChangeDetectionStrategy`](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/enum.html#changedetectionstrategy) feature could be used to add additional functionality (see commented out methods from ng2).
```TypeScript
interface ComponentFixture {
  componentInstance : T;
  nativeElement : HTMLElement; // root DOM element from elementRef
  elementRef : angular.IAugmentedJQuery;
  // debugElement : DebugElement
  // componentRef : ComponentRef<T>;
  $scope: angular.IScope; // instead of ngZone
  detectChanges: () => void; // i.e. $scope.$apply()
  destroy: () => void; // i.e. $scope.$destroy()
  // changeDetectorRef : ChangeDetectorRef;
  // checkNoChanges() : void;
  // autoDetectChanges(autoDetect?: boolean);
  // isStable() : boolean;
  // whenStable() : Promise<any>;
}
```

**Comment by aciccarello** [comment]
I've implemented a POC for this. I setup a separate project b/c it uses angular-mocks as a dependency. I'm not sure how it could be integrated. Are there plans to move to multiple scoped packages like ng2? I don't think it's really necessary but it would allow having different dependencies for the testing module.

https://github.com/aciccarello/ng-metadata-testing

**Comment by aciccarello** [comment]
Thanks for taking the time to take a look at it. That all makes sense. I'll work on integrating NgModule support. This is my first major OS contribution so I apologize if I make more work for you. Feel free to correct me if necessary.

**Comment by JamesHenry** [comment]
Yeah, thanks @aciccarello! I would say it is definitely fair to assume that all Angular 1 projects have angular-mocks as a peerDependency already. If they don't they have bigger problems than ng-metadata utilities not working 😄

**Comment by michaelkrog** [comment]
This may be a dumb question, but it is still not clear to me how I can create a test that injects one of my own typescript classes?

Take the example from https://hotell.gitbooks.io/ng-metadata/content/docs/recipes/service.html
```Javascript
// user.service.ts
import { Inject, Injectable } from 'ng-metadata/core';

@Injectable()
export class UserService{

  hobbies: string[] = [];

  constructor( @Inject('$http') private $http: ng.IHttpService ){}

  addHobby(name: string){
     this.hobbies.push(name);
  }

  getInfo(){
    return this.$http.get('/foo/bar/info')
      .then((response)=>response.data);
  }

}
```

```Javascript
// user.component.ts
import { Component } from 'ng-metadata/core';

import { UserService } from './user.service';

@Component({
  selector:'my-user',
  providers: [ UserService ],
  template: `...`
})
export class UserComponent{}
```

Is it possible to test this scenario? It is not clear to me from https://hotell.gitbooks.io/ng-metadata/content/docs/api/testing/

**Comment by aciccarello** [comment]
@michaelkrog, currently the easiest way to do this is to use the [`getInjectableName()`](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/function.html#getinjectablename) function and the angular `$injector` service.

In the future you will be able to use angular 2-like apis such as 

```TypeScript
import { inject } from 'ng-metadata/testing';
import { UserService } from './user.service';

inject([UserService], (userService: UserService) => {
  // Use instance of UserService in test
});
```

**Comment by michaelkrog** [comment]
Ahh ok.. Got it now. I can inject a mocked service like this:

```
let authenticationServiceString = getInjectableName(AuthenticationService);
  
  beforeEach( angular.mock.module( TestModule, ($provide) => {
      $provide.value(authenticationServiceString, new MockAuthenticationService());
  }));
```

That will make my mock available as `AuthenticationService` in the component I am testing.

**Comment by aciccarello** [comment]
Yep, `angular.mock.module` also accepts an object mapping mocks. Same effect but different option for syntax.

```TypeScript
let authenticationServiceString = getInjectableName(AuthenticationService);

  beforeEach( angular.mock.module( TestModule, {
      [authenticationServiceString]: new MockAuthenticationService()
  }));
```
